-- PASS50 TikTok OAuth V1
CREATE TABLE IF NOT EXISTS p50_tiktok_oauth_connections (
  user_id CHAR(36) PRIMARY KEY,
  open_id VARCHAR(191) NOT NULL,
  union_id VARCHAR(191) NOT NULL DEFAULT '',
  display_name VARCHAR(255) NOT NULL DEFAULT '',
  username VARCHAR(191) NOT NULL DEFAULT '',
  avatar_url TEXT NULL,
  profile_deep_link TEXT NULL,
  bio_description TEXT NULL,
  is_verified TINYINT(1) NOT NULL DEFAULT 0,
  follower_count BIGINT NULL,
  following_count BIGINT NULL,
  likes_count BIGINT NULL,
  video_count BIGINT NULL,
  access_token_encrypted LONGTEXT NOT NULL,
  refresh_token_encrypted LONGTEXT NOT NULL,
  token_type VARCHAR(32) NOT NULL DEFAULT 'Bearer',
  scopes TEXT NOT NULL,
  access_expires_at DATETIME NOT NULL,
  refresh_expires_at DATETIME NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  last_error TEXT NULL,
  connected_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_refreshed_at DATETIME NULL,
  last_synced_at DATETIME NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_p50_tiktok_oauth_connection_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY uq_p50_tiktok_oauth_open_id (open_id),
  INDEX idx_p50_tiktok_oauth_status (status, access_expires_at),
  INDEX idx_p50_tiktok_oauth_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS p50_tiktok_oauth_videos (
  user_id CHAR(36) NOT NULL,
  video_id VARCHAR(191) NOT NULL,
  title VARCHAR(255) NOT NULL DEFAULT '',
  video_description TEXT NULL,
  cover_image_url TEXT NULL,
  share_url TEXT NULL,
  embed_link TEXT NULL,
  duration_seconds INT NULL,
  published_at DATETIME NULL,
  view_count BIGINT NULL,
  like_count BIGINT NULL,
  comment_count BIGINT NULL,
  share_count BIGINT NULL,
  fetched_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, video_id),
  CONSTRAINT fk_p50_tiktok_oauth_video_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_p50_tiktok_oauth_video_published (user_id, published_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
