// Connecteurs privés repliables, isolés du classement public.
const CACHE='pass50-v64-top50-heat-order';
const ASSETS=[
  './','./index.html','./mon-fil.html','./app-config.js','./content-intelligence.js?v=1.1','./mon-fil.js?v=2.1','./mobile-bottom-nav-v1.js?v=1.1','./share-center-v1.js?v=1.0','./coules-share-simple-v1.js?v=1.0','./fi-navigation-v3.js?v=1.2','./fi-engagement-v3.js?v=1.3','./live-modal-layout-v1.js?v=1.0',
  './profile-ennemi-des-djandjou.js?v=1.0','./profile-kawaii-nanami.js?v=1.0','./profile-melanie-tms.js?v=1.0','./profile-ivorian-kid.js?v=1.0','./profile-obre-marie-pascale.js?v=1.0','./profile-oustaz-diane.js?v=1.0','./profile-ismael-aka.js?v=1.0','./profile-general-camille-makosso.js?v=1.0','./profile-lolo-beaute.js?v=1.0','./profile-kim-makosso.js?v=1.0','./profile-dez-cocrane225.js?v=1.0','./profile-atoule.js?v=1.0','./profile-lionel-pcs.js?v=1.0','./profile-yasmine-fofana.js?v=1.0',
  './live-radar-v3.js?v=1.7','./live-trust-gate-v1.js?v=1.2','./live-experience-v4-1.js?v=1.4','./live-dismiss-ui-v1.js?v=1.0','./official-links-persistence-v3.js?v=3.2','./public-copy-fixes.js?v=1.1','./connector-sections-v1.js?v=1.1','./youtube-analytics-ui-v1.js?v=1.0','./meta-oauth-ui-v1.js?v=1.5','./tiktok-oauth-ui-v1.js?v=1.0','./admin-fictive-ranking-v1.js?v=1.0','./classement-fictif.html',
  './v9-tools.css?v=22.4','./v9-tools.js?v=15.5','./pass50_nouveaux_candidats_90_v19.json?v=22.8','./data-engine-ui.js?v=18.6','./manifest.webmanifest?v=22.4','./icon.svg?v=22.4','./favicon-32.png?v=22.4','./apple-touch-icon.png?v=22.4','./assets/hero-media-1.jpg','./assets/hero-media-2.jpg','./assets/hero-media-3.jpg','./assets/hero-media-4.jpg','./data-engine-ui.css?v=27.0'
];
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(ASSETS)));});
self.addEventListener('activate',event=>{event.waitUntil(Promise.all([self.clients.claim(),caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key))))]));});
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;if(event.request.mode==='navigate'){const feedPath=new URL(event.request.url).pathname.endsWith('/mon-fil.html');const fallback=feedPath?'./mon-fil.html':'./index.html';event.respondWith(fetch(event.request,{cache:'no-store'}).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(fallback,copy));return response;}).catch(()=>caches.match(fallback)));return;}const url=new URL(event.request.url);const forceFresh=['.js','.css','.html','.php'].some(extension=>url.pathname.endsWith(extension));event.respondWith(fetch(event.request,forceFresh?{cache:'no-store'}:undefined).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy));return response;}).catch(()=>caches.match(event.request)));});
