'use strict';

const PASS50_V9={photoCandidates:[],photoProfileId:null,preview:null,previewEventId:null,news:[],newsProfileId:null,newsDays:15,linksProfileId:null,linksSearch:''};

function p50v9IsGenericLink(url=''){
  try{const u=new URL(url);return !u.pathname||u.pathname==='/'||/(search|results|explore\/search)/i.test(u.pathname)||u.searchParams.has('search_query')||u.searchParams.has('q');}catch{return true}
}
function p50v9IsDirectPlatformLink(platform,url=''){
  if(!url||p50v9IsGenericLink(url))return false;
  try{const u=new URL(url),h=u.hostname.toLowerCase(),path=u.pathname;
    const rules={
      Instagram:()=>h.endsWith('instagram.com')&&/^\/[A-Za-z0-9._-]+\/?$/.test(path),
      TikTok:()=>h.endsWith('tiktok.com')&&/^\/@[^/]+\/?$/.test(path),
      YouTube:()=>h.includes('youtube.com')&&/^\/(?:@|channel\/|c\/|user\/)/.test(path),
      Facebook:()=>h.endsWith('facebook.com')&&path.length>1&&!path.startsWith('/search'),
      Snapchat:()=>h.endsWith('snapchat.com')&&/^\/add\/[^/]+\/?$/.test(path),
      LinkedIn:()=>h.endsWith('linkedin.com')&&/^\/(?:in|company)\//.test(path),
      X:()=> (h==='x.com'||h.endsWith('twitter.com'))&&/^\/[A-Za-z0-9_]+\/?$/.test(path),
      Web:()=>/^https?:$/.test(u.protocol)&&Boolean(h)&&path!=='/'
    };return rules[platform]?rules[platform]():false;
  }catch{return false}
}
function p50v9OfficialLinks(p){const qualityOk=Number(p?.quality?.social||0)>=90;return Object.entries(p?.links||{}).filter(([platform,url])=>{const account=p?.socialAccounts?.[platform];if(account?.visible===false)return false;if(!p50v9IsDirectPlatformLink(platform,url))return false;const checked=p?.linkChecks?.[platform]?.status;return qualityOk||checked==='ok'||checked==='blocked_but_exists';});}
function p50v9ExactContentLink(url=''){return /^https?:\/\//i.test(url)&&!p50v9IsGenericLink(url)}
function p50v9ApplyPatch(){
  const socialPlatforms=['Instagram','TikTok','Facebook','YouTube','Snapchat','X','LinkedIn','Web'];
  db.profiles.forEach(p=>{
    p.linkChecks=p.linkChecks||{};p.links=p.links||{};p.socialAccounts=p.socialAccounts||{};
    socialPlatforms.forEach(platform=>{
      const url=p.links[platform]||p.socialAccounts[platform]?.url||'';
      if(url&&!p.links[platform])p.links[platform]=url;
      if(!p.linkChecks[platform])p.linkChecks[platform]={status:url?(p50v9IsDirectPlatformLink(platform,url)?'pending':'search_not_official'):'invalid',checkedAt:null,message:url?'Validation requise':'Non renseigné'};
      const previous=p.socialAccounts[platform]||{};
      p.socialAccounts[platform]={
        handle:String(previous.handle||''),
        url:String(previous.url||url||''),
        followers:Number(previous.followers||0),
        visible:previous.visible!==false,
        confirmed:previous.confirmed===true||['ok','blocked_but_exists'].includes(p.linkChecks[platform]?.status),
        checkedAt:previous.checkedAt||p.linkChecks[platform]?.checkedAt||null,
        status:previous.status||p.linkChecks[platform]?.status||'invalid',
        message:previous.message||p.linkChecks[platform]?.message||''
      };
    });
    if(!p.photoPosition)p.photoPosition='50% 50%';
  });
  db.events=(db.events||[]).map(e=>({...e,coverStatus:e.coverStatus||'missing',coverUrl:e.coverUrl||'',coverCandidateUrl:e.coverCandidateUrl||'',coverSource:e.coverSource||'',coverNote:e.coverNote||''}));
  db.content.forEach(c=>{const ev=primaryEvent(c.profileId);if(ev&&p50v9ExactContentLink(ev.url)&&!p50v9ExactContentLink(c.url))c.url=ev.url;});
  db.version=Math.max(Number(db.version||0),11);
}
p50v9ApplyPatch();save();render();
const p50v9CloudPatchTimer=setInterval(()=>{if(window.__pass50CloudReady){p50v9ApplyPatch();save();render();clearInterval(p50v9CloudPatchTimer)}},500);
setTimeout(()=>clearInterval(p50v9CloudPatchTimer),20000);

function p50v9OpenTool(title,html){$('#toolTitle').textContent=title;$('#toolBody').innerHTML=html;open('toolModal')}
function p50v9CloseTool(){close('toolModal')}
function p50v9StatusClass(status){return ['ok','blocked_but_exists'].includes(status)?'ok':status==='pending'?'pending':'bad'}
function p50v9StatusText(status){return ({ok:'OFFICIEL',blocked_but_exists:'À CONFIRMER',pending:'NON TESTÉ',search_not_official:'RECHERCHE',wrong_platform:'MAUVAIS RÉSEAU',broken:'CASSÉ',invalid:'INVALIDE'})[status]||String(status||'NON TESTÉ').toUpperCase()}

const p50v8RenderAdminPane=renderAdminPane;
renderAdmin=function(){const menu=`<div class="admin-menu"><button class="btn ${ui.adminTab==='signals'?'primary':''}" data-admin-tab="signals">Signaux</button><button class="btn ${ui.adminTab==='profiles'?'primary':''}" data-admin-tab="profiles">Influenceurs</button><button class="btn ${ui.adminTab==='links'?'primary':''}" data-admin-tab="links">Réseaux sociaux</button><button class="btn ${ui.adminTab==='media'?'primary':''}" data-admin-tab="media">Médias</button><button class="btn ${ui.adminTab==='news'?'primary':''}" data-admin-tab="news">Actualité</button><button class="btn ${ui.adminTab==='ranking'?'primary':''}" data-admin-tab="ranking">Classement</button><button class="btn ${ui.adminTab==='data'?'primary':''}" data-admin-tab="data">Données</button></div>`;$('#adminBody').innerHTML=`<div class="admin-grid">${menu}<div class="admin-pane" id="adminPane"></div></div>`;renderAdminPane()}
renderAdminPane=function(){if(ui.adminTab==='profiles')return p50v9RenderProfiles();if(ui.adminTab==='links')return p50v9RenderLinks();if(ui.adminTab==='news')return p50v9RenderNews();return p50v8RenderAdminPane()}

function p50v9RenderProfiles(){
  const pane=$('#adminPane');
  pane.innerHTML=`<div class="media-hint"><strong>Gestion des influenceurs :</strong> modifie la fiche générale ou ouvre directement les réseaux sociaux à ajouter manuellement.</div><div class="admin-toolbar"><input id="profileSearch" placeholder="Rechercher un influenceur" style="padding:10px;border-radius:12px;border:1px solid var(--line);background:#0f130f;color:white"><button class="btn small" id="addProfileBtn">Ajouter un influenceur</button></div><div class="admin-table-wrap"><table class="admin-table" style="min-width:760px"><thead><tr><th>Nom</th><th>Zone</th><th>Score</th><th>Réseaux</th><th>Éligible</th><th>Actions</th></tr></thead><tbody id="profileAdminRows">${adminProfileRows(db.profiles)}</tbody></table></div>`;
}
adminProfileRows=function(list){const topIds=new Set(ranking().slice(0,50).map(p=>p.id));return list.map(p=>{const links=p50v9OfficialLinks(p),declared=Object.values(p.links||{}).filter(Boolean).length;return `<tr class="${topIds.has(p.id)?'is-top50':''}"><td><strong>${p.name}</strong>${topIds.has(p.id)?'<span class="top50-marker">TOP 50</span>':''}<div class="hub-detail">${p.handle||''}</div></td><td>${p.region}</td><td>${score(p)}</td><td><strong>${links.length}</strong> validé${links.length>1?'s':''}<div class="hub-detail">${declared} renseigné${declared>1?'s':''}</div></td><td>${p.eligible&&p.alive?'Oui':'Non'}</td><td><div class="profile-admin-actions"><button class="btn small edit-profile" data-id="${p.id}">Modifier la fiche</button><button class="btn small primary edit-profile-links" data-id="${p.id}">Ajouter les réseaux</button></div></td></tr>`}).join('')}

mediaCard=function(kind,item){const isProfile=kind==='profile',name=isProfile?item.name:(profile(item.profileId)?.name+' · '+item.title),status=isProfile?item.photoStatus:item.coverStatus,url=isProfile?candidatePhoto(item):(item.coverUrl||item.coverCandidateUrl||''),source=isProfile?item.photoSource:item.coverSource,note=isProfile?item.photoNote:item.coverNote,fallback=isProfile?item.initials:(item.icon||'▶');return `<article class="media-card"><div class="media-preview ${isProfile?'':'cover'}"><span>${fallback}</span>${url?`<img src="${safeAttr(url)}" alt="${safeAttr(name)}" referrerpolicy="no-referrer" onerror="this.style.display='none'">`:''}<span class="media-state ${status}">${mediaStatusText(status)}</span></div><div class="media-body"><h4>${name}</h4><div class="media-source">${source||'Aucune source enregistrée'}${note?`<br>${note}`:''}</div><div class="media-url-row"><input class="media-url-input" data-kind="${kind}" data-id="${item.id}" value="${safeAttr(url)}" placeholder="Coller une URL d’image"><button class="btn small media-save-url" data-kind="${kind}" data-id="${item.id}">Ajouter</button></div><div class="media-actions">${isProfile?`<button class="btn small media-discover" data-id="${item.id}">🔎 Rechercher gratuitement</button>`:`<button class="btn small event-preview" data-id="${item.id}">🎬 Analyser le lien</button>`}<button class="btn small primary media-validate" data-kind="${kind}" data-id="${item.id}">Valider</button><button class="btn small danger media-reject" data-kind="${kind}" data-id="${item.id}">Rejeter</button><label class="file-label">Importer${isProfile?' une photo':' une couverture'}<input type="file" accept="image/*" class="media-file" data-kind="${kind}" data-id="${item.id}"></label></div></div></article>`}
renderMediaPane=function(pane){const order={pending:0,missing:1,rejected:2,validated:3},profiles=[...db.profiles].sort((a,b)=>(order[a.photoStatus]??9)-(order[b.photoStatus]??9)),events=[...db.events].sort((a,b)=>(order[a.coverStatus]??9)-(order[b.coverStatus]??9));pane.innerHTML=`<div class="media-hint"><strong>Règle stricte :</strong> aucune photo ou couverture n’est téléchargée sans confirmation humaine qu’elle représente le bon profil ou le bon contenu.</div><div class="free-tools"><span class="free-pill">Openverse</span><span class="free-pill">Wikimedia Commons</span><span class="free-pill">Wikipédia</span><span class="free-pill">TikTok oEmbed</span><span class="free-pill">YouTube oEmbed</span></div><div class="admin-toolbar"><button class="btn primary" id="bulkPhotoSearch">Rechercher les photos du Top 10</button><button class="btn" id="bulkCoverSearch">Analyser les couvertures du Top 10</button></div><div class="section-head"><div class="section-title">Photos des influenceurs</div><span class="muted">${profiles.filter(x=>x.photoStatus==='pending').length} à valider</span></div><div class="media-grid">${profiles.map(p=>mediaCard('profile',p)).join('')}</div><div class="section-head" style="margin-top:22px"><div class="section-title">Couvertures des éléments déclencheurs</div><span class="muted">Vidéos, articles et événements</span></div><div class="media-grid">${events.map(e=>mediaCard('event',e)).join('')}</div>`}

function p50v9PlatformIcon(platform){return ({Instagram:'◎',TikTok:'♪',Facebook:'f',YouTube:'▶',Snapchat:'◉',X:'𝕏',LinkedIn:'in',Web:'⌂'})[platform]||'•'}
function p50v9RenderLinks(){
  const pane=$('#adminPane'),all=[...db.profiles].sort((a,b)=>a.name.localeCompare(b.name,'fr'));
  const filtered=all.filter(p=>!PASS50_V9.linksSearch||`${p.name} ${p.handle}`.toLowerCase().includes(PASS50_V9.linksSearch.toLowerCase()));
  if(!PASS50_V9.linksProfileId||!all.some(p=>p.id===PASS50_V9.linksProfileId))PASS50_V9.linksProfileId=(ranking()[0]||all[0])?.id||null;
  const selected=profile(PASS50_V9.linksProfileId)||filtered[0]||all[0];if(selected)PASS50_V9.linksProfileId=selected.id;
  const verified=all.reduce((n,p)=>n+p50v9OfficialLinks(p).length,0);
  pane.innerHTML=`<div class="official-links-shell"><div class="media-hint"><strong>Ajout manuel des réseaux sociaux :</strong> sélectionne un influenceur, renseigne son identifiant, l’URL officielle et son nombre d’abonnés. Active uniquement les comptes que tu souhaites afficher sur sa fiche publique.</div><div class="official-links-toolbar"><div class="field"><label>Rechercher un influenceur</label><input id="officialLinksSearch" value="${safeAttr(PASS50_V9.linksSearch)}" placeholder="Nom ou identifiant"></div><div class="field"><label>Influenceur</label><select id="officialLinksProfile">${filtered.map(p=>`<option value="${p.id}" ${p.id===selected?.id?'selected':''}>${p.name}</option>`).join('')}</select></div><div class="official-links-kpi"><strong>${all.length}</strong><span>profils suivis</span></div><div class="official-links-kpi"><strong>${verified}</strong><span>liens validés</span></div></div>${selected?p50v9LinkCard(selected):'<div class="tool-empty">Aucun profil trouvé.</div>'}</div>`;
}
function p50v9Account(p,platform){
  const check=p.linkChecks?.[platform]||{status:'invalid',checkedAt:null,message:''},stored=p.socialAccounts?.[platform]||{};
  return {handle:String(stored.handle||''),url:String(stored.url||p.links?.[platform]||''),followers:Number(stored.followers||0),visible:stored.visible!==false,confirmed:stored.confirmed===true||['ok','blocked_but_exists'].includes(check.status),checkedAt:stored.checkedAt||check.checkedAt||null,status:stored.status||check.status||'invalid',message:stored.message||check.message||''};
}
function p50v9Followers(value){const n=Number(value||0);return n>0?new Intl.NumberFormat('fr-FR').format(n):'Non renseigné'}
function p50v9LinkCard(p){
  const order=['Instagram','TikTok','Facebook','YouTube','Snapchat','X','LinkedIn','Web'],plats=[...new Set([...order,...(p.platforms||[]),...Object.keys(p.links||{}),...Object.keys(p.socialAccounts||{})])];
  return `<article class="link-card official-editor" data-link-profile="${p.id}"><div class="link-card-head"><div><div class="official-profile-name">${p.name}${ranking().slice(0,50).some(x=>x.id===p.id)?'<span class="top50-marker">TOP 50</span>':''}</div><div class="muted">${p.handle||'Identifiant non renseigné'} · ${p.category}</div></div><div class="tool-actions"><button class="btn small" id="openLinksFI" data-id="${p.id}">Ouvrir la FI</button><button class="btn small primary save-links" data-id="${p.id}">Enregistrer les réseaux</button><button class="btn small check-links" data-id="${p.id}">Tout vérifier</button></div></div><div class="official-platform-grid">${plats.map(platform=>{const account=p50v9Account(p,platform),direct=p50v9IsDirectPlatformLink(platform,account.url);return `<section class="official-platform-row" data-platform-row="${platform}"><div class="platform-label"><span class="platform-icon">${p50v9PlatformIcon(platform)}</span><div><strong>${platform}</strong><span class="link-state ${p50v9StatusClass(account.status)}" title="${safeAttr(account.message||'')}">${p50v9StatusText(account.status)}</span></div></div><div class="platform-editor"><div class="platform-input-grid"><label><span>Nom du compte / identifiant</span><input data-link-handle="${platform}" value="${safeAttr(account.handle)}" placeholder="@identifiant"></label><label class="platform-url-field"><span>URL officielle exacte</span><input type="url" data-link-platform="${platform}" value="${safeAttr(account.url)}" placeholder="https://…"></label><label><span>Nombre d’abonnés</span><input type="number" min="0" step="1" data-link-followers="${platform}" value="${account.followers||''}" placeholder="0"></label></div><div class="platform-options"><label class="official-confirm"><input type="checkbox" data-link-visible="${platform}" ${account.visible?'checked':''}> Afficher sur la fiche publique</label><label class="official-confirm"><input type="checkbox" data-link-confirm="${platform}" ${account.confirmed?'checked':''}> Je confirme le compte officiel</label></div><div class="platform-check-meta">Abonnés : ${p50v9Followers(account.followers)} · Dernière vérification : ${account.checkedAt?new Date(account.checkedAt).toLocaleString('fr-FR'):'jamais'}${account.url&&!direct?' · URL non directe ou générique':''}</div></div><div class="platform-row-actions">${account.url?`<a class="btn small" href="${safeAttr(account.url)}" target="_blank" rel="noopener">Ouvrir ↗</a><button class="btn small check-one-link" data-id="${p.id}" data-platform="${platform}">Tester le lien</button>`:'<span class="muted">Non renseigné</span>'}</div></section>`}).join('')}</div></article>`;
}
function p50v9SaveLinks(id,card,options={}){
  const p=profile(id);if(!p||!card)return false;
  p.links=p.links||{};p.linkChecks=p.linkChecks||{};p.socialAccounts=p.socialAccounts||{};p.platforms=p.platforms||[];
  const invalid=[];let verified=0;
  card.querySelectorAll('[data-link-platform]').forEach(input=>{
    const platform=input.dataset.linkPlatform,url=input.value.trim(),handle=card.querySelector(`[data-link-handle="${platform}"]`)?.value.trim()||'',followers=Math.max(0,Number(card.querySelector(`[data-link-followers="${platform}"]`)?.value||0)),visible=card.querySelector(`[data-link-visible="${platform}"]`)?.checked!==false,confirmed=card.querySelector(`[data-link-confirm="${platform}"]`)?.checked===true,direct=url?p50v9IsDirectPlatformLink(platform,url):false,previous=p.socialAccounts[platform]||{};
    let status='invalid',message='Non renseigné',checkedAt=previous.checkedAt||p.linkChecks[platform]?.checkedAt||null;
    if(url&&confirmed&&direct){status='ok';message='Compte officiel confirmé manuellement';checkedAt=new Date().toISOString();verified++;}
    else if(url&&confirmed&&!direct){status='invalid';message='Le lien doit pointer directement vers le compte officiel';invalid.push(platform);}
    else if(url){status=direct?'pending':'search_not_official';message=direct?'Confirmation officielle requise':'Lien de recherche ou page générique refusé';}
    if(url){p.links[platform]=url;if(!p.platforms.includes(platform))p.platforms.push(platform);}else{delete p.links[platform];p.platforms=p.platforms.filter(x=>x!==platform);}
    p.linkChecks[platform]={status,checkedAt,message};
    p.socialAccounts[platform]={handle,url,followers,visible,confirmed:confirmed&&direct,checkedAt,status,message};
  });
  p.quality=p.quality||{};p.quality.social=verified>0?Math.max(90,Number(p.quality.social||0)):0;
  save();render();p50v9RenderLinks();
  if(!options.silent)toast(invalid.length?`Enregistré, mais ${invalid.join(', ')} : lien officiel direct requis`:'Réseaux sociaux enregistrés');
  return invalid.length===0;
}
async function p50v9CheckLinks(id,card){
  const p=profile(id);if(!p||!card)return;p50v9SaveLinks(id,card,{silent:true});const fresh=document.querySelector(`[data-link-profile="${id}"]`),btn=fresh?.querySelector('.check-links');if(btn){btn.disabled=true;btn.textContent='Vérification…';}
  try{const data=await apiFetch('link-check.php',{method:'POST',body:{links:p.links}});p.linkChecks={...p.linkChecks,...Object.fromEntries(Object.entries(data.results||{}).map(([k,v])=>[k,{...v,checkedAt:data.checkedAt}]))};Object.entries(data.results||{}).forEach(([platform,v])=>{p.socialAccounts[platform]={...p50v9Account(p,platform),status:v.status,message:v.message||'',checkedAt:data.checkedAt,confirmed:['ok','blocked_but_exists'].includes(v.status)};});save();p50v9RenderLinks();toast('Liens contrôlés');}catch(err){toast(err.message||'Contrôle impossible');p50v9RenderLinks()}
}
async function p50v9CheckSingleLink(id,platform){
  const p=profile(id),card=document.querySelector(`[data-link-profile="${id}"]`);if(!p||!card)return;p50v9SaveLinks(id,card,{silent:true});const url=p.links?.[platform];if(!url)return toast('Renseigne d’abord une URL');
  try{const data=await apiFetch('link-check.php',{method:'POST',body:{links:{[platform]:url}}}),result=data.results?.[platform]||{status:'pending',message:'Aucun résultat'};p.linkChecks[platform]={...result,checkedAt:data.checkedAt||new Date().toISOString()};p.socialAccounts[platform]={...p50v9Account(p,platform),status:result.status,message:result.message||'',checkedAt:p.linkChecks[platform].checkedAt,confirmed:['ok','blocked_but_exists'].includes(result.status)};save();p50v9RenderLinks();toast(`Lien ${platform} contrôlé`);}catch(err){toast(err.message||'Contrôle impossible')}
}

function p50v9RenderNews(){
  const pane=$('#adminPane'),profiles=[...db.profiles].sort((a,b)=>a.name.localeCompare(b.name,'fr'));
  pane.innerHTML=`<div class="news-admin-shell"><div class="media-hint"><strong>Actualité et élément déclencheur :</strong> cherche une actualité ou colle directement le lien original. Rien n’apparaît dans la FI tant que tu n’as pas confirmé le lien.</div><div class="news-search-panel"><div class="field"><label>Influenceur</label><select id="newsProfile">${profiles.map(p=>`<option value="${p.id}" ${p.id===PASS50_V9.newsProfileId?'selected':''}>${p.name}</option>`).join('')}</select></div><div class="field"><label>Période</label><select id="newsDays"><option value="2">2 jours</option><option value="7">7 jours</option><option value="15" selected>15 jours</option><option value="30">30 jours</option><option value="60">60 jours</option><option value="90">90 jours</option></select></div><button class="btn primary" id="searchNewsBtn">Rechercher l’actualité</button></div><form id="manualBuzzForm" class="manual-buzz-form"><div class="section-title">Valider manuellement le lien original de la FI</div><div class="two"><div class="field"><label>Type</label><select name="type"><option>Vidéo</option><option>Article</option><option>Déclaration</option><option>Émission</option><option>Événement</option><option>Publication</option></select></div><div class="field"><label>Plateforme</label><select name="platform"><option>Instagram</option><option>TikTok</option><option>Facebook</option><option>YouTube</option><option>Web</option></select></div></div><div class="field"><label>Titre affiché dans la FI</label><input name="title" placeholder="Décris brièvement ce qui provoque le buzz" required></div><div class="field"><label>URL exacte du contenu original</label><input type="url" name="url" placeholder="https://…" required></div><label class="tool-check"><input type="checkbox" name="confirmedOriginal" required> Je confirme qu’il s’agit du contenu original lié à ce buzz.</label><button class="btn primary" type="submit">VALIDER POUR LA FI</button></form><div id="newsResults"><div class="tool-empty">Choisissez un profil puis lancez la recherche.</div></div></div>`;
  const days=$('#newsDays');if(days)days.value=String(PASS50_V9.newsDays||15);
}
async function p50v9SearchNews(){const id=$('#newsProfile').value,p=profile(id),days=Number($('#newsDays').value||15),box=$('#newsResults');PASS50_V9.newsProfileId=id;PASS50_V9.newsDays=days;box.innerHTML='<div class="tool-loading">Recherche des sources en cours…</div>';try{const data=await apiFetch('news-discover.php',{method:'POST',body:{name:p.name,days}});PASS50_V9.news=data.articles||[];const warning=data.warning?`<div class="news-warning">${data.warning}</div>`:'';box.innerHTML=warning+(PASS50_V9.news.length?PASS50_V9.news.map((a,i)=>`<article class="news-card">${a.image?`<img src="${safeAttr(a.image)}" alt="" referrerpolicy="no-referrer" onerror="this.style.display='none'">`:'<div class="trigger-thumb">📰</div>'}<div><h4>${a.title||'Article sans titre'}</h4><div class="tool-meta">${a.domain||''} · ${a.date||''} · ${a.source||data.source||''}</div><label class="tool-check"><input type="checkbox" class="confirm-news-original" data-index="${i}"> Je confirme que ce lien est l’élément original à afficher dans la FI.</label><div class="tool-actions"><a class="btn small" href="${safeAttr(a.url)}" target="_blank" rel="noopener">Ouvrir l’original ↗</a><button class="btn small primary use-news" data-index="${i}">Valider pour la FI</button></div></div></article>`).join(''):'<div class="tool-empty">Aucun résultat récent trouvé. Utilise le formulaire manuel ci-dessus.</div>')}catch(err){box.innerHTML=`<div class="news-warning"><strong>Recherche momentanément indisponible.</strong><br>${safeAttr(err.message||'La source distante ne répond pas.')}<br>Tu peux toujours valider le lien original manuellement ci-dessus.</div>`}}
function p50v9SaveTrigger(id,patch,source='manual'){const p=profile(id);if(!p||!p50v9ExactContentLink(patch.url))throw new Error('URL originale invalide');let ev=primaryEvent(id);const finalPatch={...patch,originalUrlValidated:true,originalUrlValidatedAt:new Date().toISOString(),originalUrlSource:source,confidence:'élevée'};if(ev)Object.assign(ev,finalPatch);else db.events.push({id:'trigger_'+id+'_'+Date.now(),profileId:id,...finalPatch});const content=db.content.find(c=>c.profileId===id);if(content){content.url=patch.url;content.originalUrlValidated=true;}save();render();toast('Lien original validé pour la FI')}
function p50v9UseNews(index){const a=PASS50_V9.news[index],id=PASS50_V9.newsProfileId,p=profile(id),confirmBox=document.querySelector(`.confirm-news-original[data-index="${index}"]`);if(!a||!p)return;if(!confirmBox?.checked)return toast('Confirme d’abord qu’il s’agit du lien original');p50v9SaveTrigger(id,{type:'Article',title:a.title||`Actualité concernant ${p.name}`,platforms:['Web'],metric:'Actualité récente',publishedLabel:a.date||`Sur ${PASS50_V9.newsDays} jours`,reason:'Actualité sélectionnée et lien original vérifié manuellement.',url:a.url,icon:'📰',coverCandidateUrl:a.image||'',coverUrl:'',coverStatus:a.image?'pending':'missing',coverSource:a.domain||a.source||'Actualité',coverNote:'Couverture à valider séparément.'},a.source||'news-search')}

async function p50v9DiscoverPhotos(id,openResults=true){const p=profile(id);if(!p)return null;const officialUrls=p50v9OfficialLinks(p).map(([,url])=>url);const data=await apiFetch('media-discover.php',{method:'POST',body:{profileId:p.id,name:p.name,handle:p.handle,officialUrls}});if(openResults)p50v9ShowPhotoCandidates(p,data);return data}
function p50v9ShowPhotoCandidates(p,data){PASS50_V9.photoCandidates=data.candidates||[];PASS50_V9.photoProfileId=p.id;const cards=PASS50_V9.photoCandidates.map((c,i)=>`<article class="tool-card"><img src="${safeAttr(c.previewUrl||c.url)}" alt="Proposition pour ${safeAttr(p.name)}" referrerpolicy="no-referrer" onerror="this.style.display='none'"><h4>${c.sourceName||'Source'}</h4><div class="tool-meta">Confiance ${c.confidence||'moyenne'} · ${c.reason||''}</div><div class="tool-license">${c.attribution?`Attribution : ${c.attribution}<br>`:''}${c.license?`Licence : ${c.license}`:''}</div><label class="tool-check"><input type="checkbox" class="confirm-photo" data-index="${i}"> Je confirme que cette photo représente clairement ${p.name}.</label><div class="tool-actions"><a class="btn small" href="${safeAttr(c.sourcePage||c.url)}" target="_blank" rel="noopener">Voir la source ↗</a><button class="btn small" data-propose-photo="${i}">Proposer sans télécharger</button><button class="btn small primary" data-download-photo="${i}">Valider et télécharger</button></div></article>`).join('');p50v9OpenTool(`Photos proposées · ${p.name}`,`<div class="media-hint">${data.rule||''}</div><div class="free-tools">${(data.freeSources||[]).map(x=>`<span class="free-pill">${x}</span>`).join('')}</div>${cards?`<div class="tool-grid">${cards}</div>`:`<div class="tool-empty">Aucune photo suffisamment fiable. Le script n’a rien téléchargé.<br><br><a class="btn small" href="${safeAttr(data.googleImagesUrl||'#')}" target="_blank" rel="noopener">Recherche manuelle Google Images ↗</a></div>`}`)}
function p50v9ProposePhoto(index){const p=profile(PASS50_V9.photoProfileId),c=PASS50_V9.photoCandidates[index];if(!p||!c)return;p.photoCandidateUrl=c.previewUrl||c.url;p.photoUrl='';p.photoStatus='pending';p.photoSource=c.sourceName||'Source gratuite';p.photoNote='Proposition non téléchargée · validation requise';save();render();renderAdminPane();p50v9CloseTool();toast('Photo proposée, non publiée')}
async function p50v9DownloadPhoto(index){const p=profile(PASS50_V9.photoProfileId),c=PASS50_V9.photoCandidates[index],check=$(`.confirm-photo[data-index="${index}"]`);if(!p||!c)return;if(!check?.checked)return toast('Confirme d’abord que la photo représente bien la personne');try{const data=await apiFetch('media-download.php',{method:'POST',body:{kind:'profile',profileId:p.id,profileName:p.name,url:c.url,sourcePage:c.sourcePage,confirmedRepresentation:true}});p.photoUrl=data.url;p.photoCandidateUrl=data.url;p.photoStatus='validated';p.photoSource=[c.sourceName,c.attribution,c.license].filter(Boolean).join(' · ');p.photoNote='Validé manuellement puis copié sur IONOS';save();render();renderAdminPane();p50v9CloseTool();toast('Photo validée et enregistrée sur IONOS')}catch(err){toast(err.message||'Téléchargement impossible')}}

async function p50v9PreviewEvent(id,openResults=true){const ev=db.events.find(e=>e.id===id);if(!ev||!p50v9ExactContentLink(ev.url)){if(openResults)toast('Ajoute d’abord le lien exact de la vidéo ou de l’article');return null}const data=await apiFetch('content-preview.php',{method:'POST',body:{url:ev.url}});if(openResults)p50v9ShowEventPreview(ev,data);return data}
function p50v9ShowEventPreview(ev,data){PASS50_V9.preview=data;PASS50_V9.previewEventId=ev.id;const image=data.thumbnail?`<img src="${safeAttr(data.thumbnail)}" alt="Couverture" referrerpolicy="no-referrer" onerror="this.style.display='none'">`:'<div class="trigger-thumb">🎬</div>';p50v9OpenTool(`Couverture · ${profile(ev.profileId)?.name||''}`,`<div class="tool-grid"><article class="tool-card">${image}<h4>${data.title||ev.title}</h4><div class="tool-meta">${data.platform} · ${data.author||''} · ${data.source||''}</div>${data.thumbnail?`<label class="tool-check"><input type="checkbox" id="confirmCover"> Je confirme que cette couverture correspond au contenu original.</label>`:''}<div class="tool-actions"><a class="btn small" href="${safeAttr(data.canonicalUrl||data.url)}" target="_blank" rel="noopener">Ouvrir l’original ↗</a>${data.thumbnail?'<button class="btn small" id="proposeCover">Proposer</button><button class="btn small primary" id="downloadCover">Valider et télécharger</button>':''}</div></article></div>`)}
function p50v9ProposeCover(){const ev=db.events.find(e=>e.id===PASS50_V9.previewEventId),d=PASS50_V9.preview;if(!ev||!d?.thumbnail)return;ev.coverCandidateUrl=d.thumbnail;ev.coverUrl='';ev.coverStatus='pending';ev.coverSource=d.source||d.platform;ev.coverNote='Couverture proposée automatiquement, validation requise.';if(d.canonicalUrl)ev.url=d.canonicalUrl;if(d.title)ev.title=d.title;save();render();renderAdminPane();p50v9CloseTool();toast('Couverture proposée')}
async function p50v9DownloadCover(){const ev=db.events.find(e=>e.id===PASS50_V9.previewEventId),d=PASS50_V9.preview;if(!ev||!d?.thumbnail)return;if(!$('#confirmCover')?.checked)return toast('Confirme d’abord la couverture');const p=profile(ev.profileId);try{const data=await apiFetch('media-download.php',{method:'POST',body:{kind:'event',itemId:ev.id,itemName:ev.title,profileId:p?.id||ev.id,profileName:p?.name||ev.title,url:d.thumbnail,sourcePage:d.canonicalUrl||d.url,confirmedRepresentation:true}});ev.coverUrl=data.url;ev.coverCandidateUrl=data.url;ev.coverStatus='validated';ev.coverSource=d.source||d.platform;ev.coverNote='Validé manuellement puis copié sur IONOS';if(d.canonicalUrl)ev.url=d.canonicalUrl;if(d.title)ev.title=d.title;save();render();renderAdminPane();p50v9CloseTool();toast('Couverture validée et enregistrée')}catch(err){toast(err.message||'Téléchargement impossible')}}

async function p50v9BulkPhotos(){const list=ranking().slice(0,10).filter(p=>p.photoStatus!=='validated');let found=0;for(const p of list){try{const data=await p50v9DiscoverPhotos(p.id,false),c=data?.candidates?.[0];if(c){p.photoCandidateUrl=c.previewUrl||c.url;p.photoUrl='';p.photoStatus='pending';p.photoSource=c.sourceName||'Source gratuite';p.photoNote='Première proposition automatique. Aucun téléchargement avant confirmation.';found++}}catch(e){console.warn(e)}}save();render();renderAdminPane();toast(`${found} proposition${found>1?'s':''} à valider · aucun téléchargement automatique`)}
async function p50v9BulkCovers(){const ids=ranking().slice(0,10).map(p=>primaryEvent(p.id)).filter(Boolean);let found=0;for(const ev of ids){if(!p50v9ExactContentLink(ev.url))continue;try{const d=await p50v9PreviewEvent(ev.id,false);if(d?.thumbnail){ev.coverCandidateUrl=d.thumbnail;ev.coverUrl='';ev.coverStatus='pending';ev.coverSource=d.source||d.platform;ev.coverNote='Proposition automatique, non téléchargée.';found++}}catch(e){console.warn(e)}}save();render();renderAdminPane();toast(`${found} couverture${found>1?'s':''} à valider`)}

const p50v8OpenProfile=openProfile;
function p50v9SocialLabel(platform){return ({Facebook:'f Facebook',YouTube:'▶ YouTube',Instagram:'◎ Instagram',TikTok:'♪ TikTok',Snapchat:'◉ Snapchat',X:'𝕏 X',LinkedIn:'in LinkedIn',Web:'⌂ Site'})[platform]||platform}
openProfile=function(id){
  const top50=document.getElementById('top50Modal'),profileWasOpen=document.getElementById('profileModal')?.classList.contains('show');
  if(top50?.classList.contains('show')){profileReturnContext={modalId:'top50Modal',scrollTop:top50.querySelector('.modal-box')?.scrollTop||0,profileId:id};close('top50Modal');}else if(!profileWasOpen){profileReturnContext=null;}
  const p=profile(id),u=userPrefs(),bars=[31,38,42,36,51,59,63,70,66,79,85,score(p)],links=p50v9OfficialLinks(p);$('#profileBody').innerHTML=`<div class="profile-grid"><div class="left">${avatarHtml(p)}<div class="card-actions"><button class="btn fav ${u?.favorites.includes(id)?'on':''}" data-id="${id}">${u?.favorites.includes(id)?'★ Favori':'☆ Favori'}</button><button class="btn follow ${u?.following.includes(id)?'on':''}" data-id="${id}">${u?.following.includes(id)?'Ne plus suivre':'＋ Suivre'}</button></div></div><div><div class="eyebrow">#${ranking().findIndex(x=>x.id===id)+1} · ${p.category}</div><h2 style="font-size:39px;margin:7px 0 2px">${p.name}</h2><div class="handle">${p.handle}</div><div style="margin-top:11px">${p.badges.map(badgeHtml).join(' ')||'<span class="muted">Aucun badge actif</span>'}</div><div class="stats"><div class="stat"><span class="muted">Trend Score</span><b>${score(p)}/100</b></div><div class="stat"><span class="muted">Évolution</span><b>${arrow(p)}</b></div><div class="stat"><span class="muted">Âge</span><b style="font-size:18px">${ageText(p)}</b></div><div class="stat"><span class="muted">Réseaux officiels</span><b>${links.length}</b></div></div>${eventHtml(p)}<div class="chart">${bars.map(h=>`<div class="bar" style="height:${Math.max(8,h)}%"></div>`).join('')}</div><div class="fi-social-links">${links.map(([x,url])=>`<a class="btn small fi-social ${x.toLowerCase()}" href="${safeAttr(url)}" target="_blank" rel="noopener">${p50v9SocialLabel(x)} ↗</a>`).join('')}</div>${links.length===0?'<div class="platform-hidden-note">Aucun lien officiel direct n’est encore validé. Les liens de recherche ne sont pas affichés au public.</div>':''}</div></div>`;open('profileModal')}

eventHtml=function(p){const e=primaryEvent(p.id);if(!e)return `<div class="trigger-empty"><strong>Élément déclencheur non encore validé</strong><div style="margin-top:5px">Le profil est classé sur la base de plusieurs signaux, mais aucun contenu principal n’a encore été sélectionné.</div></div>`;const originalOk=e.originalUrlValidated===true&&p50v9ExactContentLink(e.url),link=originalOk?`<a class="btn small primary" href="${safeAttr(e.url)}" target="_blank" rel="noopener">Voir l’élément original ↗</a>`:'<span class="muted">Lien original à valider dans Administration → Actualité</span>';return `<section class="trigger-card"><div class="trigger-head"><div class="trigger-kicker">⚡ POURQUOI DANS LE TOP 10 ?</div><span class="trigger-type">${e.type}</span></div><div class="trigger-main">${triggerThumbHtml(e)}<div><div class="trigger-title">${e.title}</div><div class="trigger-meta">${e.platforms.join(' · ')} · ${e.publishedLabel} · Confiance ${e.confidence}</div><div class="trigger-reason">${e.reason}</div></div></div><div class="trigger-actions"><span class="badge hot">${e.metric}</span>${link}</div></section>`}
renderContent=function(){const content=[...db.content].sort((a,b)=>{const pa=profile(a.profileId),pb=profile(b.profileId);return score(pb)-score(pa)}).slice(0,5);$('#contentGrid').innerHTML=content.map((c,i)=>{const p=profile(c.profileId),ev=primaryEvent(c.profileId),cover=publicCover(ev),url=ev?.originalUrlValidated===true&&p50v9ExactContentLink(ev.url)?ev.url:'';const body=`${cover?`<img class="cover-bg" src="${safeAttr(cover)}" alt="" referrerpolicy="no-referrer">`:''}<div><strong>#${i+1} · ${p.name}</strong><div style="margin-top:8px">${badgeHtml(c.badge)}</div></div><div class="play">▶</div><div class="content-meta"><span>${c.platform}</span><span>${c.views} · ${c.time}</span></div>`;return url?`<a class="content-card ${cover?'has-cover':''}" href="${safeAttr(url)}" target="_blank" rel="noopener" data-content="${c.id}">${body}</a>`:`<article class="content-card ${cover?'has-cover':''}" data-content="${c.id}">${body}<div class="platform-hidden-note">Lien original à valider</div></article>`}).join('')}

document.addEventListener('click',async e=>{
  if(e.target.matches('.media-discover')){try{e.target.disabled=true;e.target.textContent='Recherche…';await p50v9DiscoverPhotos(e.target.dataset.id)}catch(err){toast(err.message||'Recherche impossible')}finally{e.target.disabled=false;e.target.textContent='🔎 Rechercher gratuitement'}}
  if(e.target.matches('[data-propose-photo]'))p50v9ProposePhoto(Number(e.target.dataset.proposePhoto));
  if(e.target.matches('[data-download-photo]'))await p50v9DownloadPhoto(Number(e.target.dataset.downloadPhoto));
  if(e.target.matches('.event-preview')){try{await p50v9PreviewEvent(e.target.dataset.id)}catch(err){toast(err.message||'Prévisualisation impossible')}}
  if(e.target.id==='proposeCover')p50v9ProposeCover();if(e.target.id==='downloadCover')await p50v9DownloadCover();
  if(e.target.id==='bulkPhotoSearch')await p50v9BulkPhotos();if(e.target.id==='bulkCoverSearch')await p50v9BulkCovers();
  const profileLinksBtn=e.target.closest('.edit-profile-links');if(profileLinksBtn){PASS50_V9.linksProfileId=profileLinksBtn.dataset.id;ui.adminTab='links';renderAdmin();}
  const saveBtn=e.target.closest('.save-links');if(saveBtn){const card=saveBtn.closest('[data-link-profile]');p50v9SaveLinks(saveBtn.dataset.id,card)}
  const checkBtn=e.target.closest('.check-links');if(checkBtn){const card=checkBtn.closest('[data-link-profile]');await p50v9CheckLinks(checkBtn.dataset.id,card)}
  const checkOne=e.target.closest('.check-one-link');if(checkOne)await p50v9CheckSingleLink(checkOne.dataset.id,checkOne.dataset.platform);
  if(e.target.id==='checkTop10Links'){for(const p of ranking().slice(0,10)){const card=document.querySelector(`[data-link-profile="${p.id}"]`);if(card)await p50v9CheckLinks(p.id,card)}toast('Top 10 contrôlé')}
  if(e.target.id==='searchNewsBtn')await p50v9SearchNews();if(e.target.matches('.use-news'))p50v9UseNews(Number(e.target.dataset.index));
  if(e.target.id==='openLinksFI')openProfile(e.target.dataset.id);
});

document.addEventListener('input',e=>{if(e.target.id==='officialLinksSearch'){PASS50_V9.linksSearch=e.target.value;p50v9RenderLinks();const input=$('#officialLinksSearch');if(input){input.focus();input.setSelectionRange(input.value.length,input.value.length);}}});
document.addEventListener('change',e=>{if(e.target.id==='officialLinksProfile'){PASS50_V9.linksProfileId=e.target.value;p50v9RenderLinks();}});
document.addEventListener('submit',e=>{if(e.target.id!=='manualBuzzForm')return;e.preventDefault();const fd=new FormData(e.target),id=$('#newsProfile')?.value;if(fd.get('confirmedOriginal')!=='on')return toast('Confirme le lien original');try{p50v9SaveTrigger(id,{type:String(fd.get('type')||'Vidéo'),title:String(fd.get('title')||''),platforms:[String(fd.get('platform')||'Web')],metric:'Élément validé',publishedLabel:'Actualité récente',reason:'Lien original vérifié et validé manuellement dans l’administration.',url:String(fd.get('url')||''),icon:'▶',coverStatus:'missing',coverUrl:'',coverCandidateUrl:''},'manual');e.target.reset();}catch(err){toast(err.message||'Lien invalide')}});

render();

// PASS50 Data Engine UI loader — preserves the current homepage layout.
(function(){
  if(!document.querySelector('link[data-pass50-data-engine]')){
    const css=document.createElement('link');
    css.rel='stylesheet';
    css.href='./data-engine-ui.css?v=3';
    css.dataset.pass50DataEngine='1';
    document.head.appendChild(css);
  }
  if(!document.querySelector('script[data-pass50-data-engine]')){
    const js=document.createElement('script');
    js.src='./data-engine-ui.js?v=3';
    js.dataset.pass50DataEngine='1';
    document.body.appendChild(js);
  }
})();
