from pathlib import Path
import re
import unittest

ROOT = Path(__file__).resolve().parents[1]
SOURCE = (ROOT / 'api' / 'live-radar-v4-source.php').read_text(encoding='utf-8')
PARSERS = (ROOT / 'api' / 'live-radar-v4-parsers.php').read_text(encoding='utf-8')
STORAGE = (ROOT / 'api' / 'live-radar-v4-storage.php').read_text(encoding='utf-8')
ENDPOINT = (ROOT / 'api' / 'live-status-v4.php').read_text(encoding='utf-8')
CLIENT = (ROOT / 'live-radar-v3.js').read_text(encoding='utf-8')
EXPERIENCE = (ROOT / 'live-experience-v4-1.js').read_text(encoding='utf-8')
CONFIG = (ROOT / 'app-config.js').read_text(encoding='utf-8')
CONFIG_EXAMPLE = (ROOT / 'api' / 'config.example.php').read_text(encoding='utf-8')
DATA_CORE = (ROOT / 'api' / 'data-engine-core.php').read_text(encoding='utf-8')
SWEEP = (ROOT / '.github' / 'workflows' / 'live-radar-sweep.yml').read_text(encoding='utf-8')
CORE_TESTS = (ROOT / 'tests' / 'live_radar_v4_core.php').read_text(encoding='utf-8')


class LiveRadarV41Tests(unittest.TestCase):
    def test_multiplatform_scope(self):
        for platform in ('TikTok', 'Facebook', 'YouTube', 'Instagram'):
            self.assertIn(platform, SOURCE + PARSERS)
        self.assertIn('p50_live_v4_parse_tiktok', PARSERS)
        self.assertIn('p50_live_v4_parse_youtube', PARSERS)

    def test_tiktok_requires_current_or_cross_family_confirmation(self):
        parser = re.search(r'function p50_live_v4_parse_tiktok\(.*?\n}', PARSERS, re.S).group(0)
        self.assertIn("$confirmed?'live':'probable'", parser)
        self.assertIn("['api','api_basic','api_webcast']", PARSERS)
        self.assertIn('p50_live_v4_tiktok_is_api_label', PARSERS)
        self.assertIn('p50_live_v4_tiktok_bodies_inconclusive', PARSERS)
        self.assertIn("'live','mobile_live','embed'", PARSERS)
        self.assertIn('proofFamilies', parser)
        self.assertIn('strictApiLabels', parser)
        self.assertIn('freshApiLabels', parser)
        self.assertIn('apiLiveStructureLabels', parser)
        self.assertIn('tiktok_confirmation_incomplete', parser)
        self.assertIn('roomEvidence', parser)
        self.assertIn('$strictApiActive', parser)
        self.assertIn('$freshApiActive', parser)
        self.assertIn('$apiLiveStructure', parser)

    def test_tiktok_end_only_beats_unconfirmed_or_stale_signals(self):
        parser = re.search(r'function p50_live_v4_parse_tiktok\(.*?\n}', PARSERS, re.S).group(0)
        self.assertIn("if($endedLabels&&!$strictApi){", parser)
        self.assertIn('tiktok_api_failed_html_ended', parser)
        self.assertIn("if($endedLabels){", parser)
        self.assertIn("return ['state'=>'offline','error'=>'tiktok_live_ended'", parser)
        self.assertIn('p50_live_v4_tiktok_owner_match', PARSERS)
        self.assertIn('p50_live_v4_tiktok_room_is_fresh', PARSERS)
        self.assertIn("!$strictApiActive", parser)
        self.assertIn('Le LIVE est terminé', CORE_TESTS)
        self.assertIn('ancienne trace HTML de fin', CORE_TESTS)
        self.assertIn('Strict Publish', CORE_TESTS)
        self.assertIn("['state']==='live'", CORE_TESTS)

    def test_unknown_ionos_does_not_hide_detected_tiktok(self):
        self.assertIn("'continuityPreserved'=>false", ENDPOINT)
        self.assertIn("status='unconfirmed'", STORAGE)
        self.assertIn('latest_probe_offline', STORAGE)
        self.assertIn("h.last_state='replay'", STORAGE)
        self.assertIn("h.last_state='live'", STORAGE)
        self.assertIn("h.last_state<>'replay'", STORAGE)

    def test_public_live_keeps_detected_tiktok_without_age_limit(self):
        active = re.search(r'function p50_live_v4_active_rows\(.*?\n}', STORAGE, re.S).group(0)
        self.assertNotIn("$platform==='TikTok'?2", active)
        self.assertIn("h.last_state='live'", active)
        self.assertIn("h.last_state<>'replay'", active)
        self.assertIn('INTERVAL {$seconds} SECOND', active)
        self.assertIn("'lastConfirmedAt'=>p50_live_v4_iso($row['last_seen_at']", active)
        self.assertIn('confirmation_grace_expired', active)
        self.assertIn('p50_live_v4_detected_live_has_no_time_limit', active)
        self.assertIn("'trustSeconds'=>p50_live_v4_trust_seconds_map()", ENDPOINT)

    def test_dismissed_stream_never_returns(self):
        self.assertIn('p50_live_dismissals', STORAGE)
        self.assertIn('p50_live_v4_is_dismissed', STORAGE)
        self.assertIn('p50_live_v4_event_identity', STORAGE)
        self.assertIn('INTERVAL 24 HOUR', STORAGE)
        self.assertIn('LEFT JOIN p50_live_dismissals', STORAGE)
        self.assertIn('d.stream_key IS NULL', STORAGE)
        self.assertIn('p50_live_v4_is_profile_suppressed', STORAGE)

    def test_replay_is_separate_from_live(self):
        self.assertIn("'state'=>'replay'", PARSERS)
        self.assertIn("elseif($stateValue==='replay')", ENDPOINT)
        self.assertIn('p50_live_v4_mark_ended', ENDPOINT)
        self.assertIn("'replay'=>0", STORAGE)
        self.assertIn('function p50_live_v4_should_end_from_probe', STORAGE)
        self.assertIn('tiktok_no_live_signal_while_live', ENDPOINT)

    def test_data_chain_starts_from_verified_links_and_ends_in_public_streams(self):
        self.assertIn("s.status='verified'", SOURCE)
        self.assertIn('p50_live_v4_store_live', ENDPOINT)
        self.assertIn("'liveStreams'=>$streams", ENDPOINT)
        self.assertIn('p50_live_v4_health_update', ENDPOINT)
        self.assertIn('p50_live_streams', STORAGE)

    def test_collection_policy_is_broader_but_probable_remains_separate(self):
        self.assertIn('P50_DATA_CONFIDENCE_THRESHOLD = 80', DATA_CORE)
        self.assertIn('min(P50_DATA_CONFIDENCE_THRESHOLD', DATA_CORE)
        self.assertIn('setting_value=VALUES(setting_value)', DATA_CORE)
        self.assertIn("'confidence_threshold' => 80", CONFIG_EXAMPLE)
        self.assertIn("elseif($stateValue==='probable'", ENDPOINT)
        self.assertNotIn("$stateValue==='probable'&&!empty($result['live'])){\n                p50_live_v4_store_live", ENDPOINT)

    def test_quick_scan_reserves_discovery_capacity(self):
        self.assertIn('$discoveryFloor=min(5,max(4,(int)floor(($batch*2)/3)))', ENDPOINT)
        self.assertIn('P50_LIVE_V4_P0_RESCAN_SECONDS', SOURCE)
        self.assertIn('P50_LIVE_V4_VERIFIED_RESCAN_SECONDS', SOURCE)
        self.assertIn('$reconfirmCap=max(0,$batch-$discoveryFloor)', ENDPOINT)
        self.assertIn('$reconfirm', ENDPOINT)
        self.assertIn("'discoveryQuota'=>$discoveryQuota", ENDPOINT)
        self.assertIn("['TikTok'=>0,'Facebook'=>1,'YouTube'=>2,'Instagram'=>3]", ENDPOINT)
        self.assertIn("$_GET['batch']??14", ENDPOINT)
        self.assertIn('p50_live_v4_discovery_rank', ENDPOINT)
        self.assertIn('$metaFloor=min(2,max(1,(int)floor($discoveryQuota/4)))', ENDPOINT)
        self.assertIn('p50_live_v4_is_graph_fresh', ENDPOINT)
        self.assertIn('passCoveragePercent', ENDPOINT)
        self.assertIn('coverageWindowSeconds', ENDPOINT)
        self.assertIn("'version'=>'4.6'", ENDPOINT)

    def test_coverage_rolling_and_unknown_first(self):
        source = (ROOT / 'api' / 'live-radar-v4-source.php').read_text(encoding='utf-8')
        self.assertIn("P50_LIVE_V4_COVERAGE_REVISION = 'LIVE-COVERAGE-ROLLING-2026-08-24-1'", source)
        self.assertIn('function p50_live_v4_coverage_stats', source)
        self.assertIn("$source['last_state']=(string)($health[$key]['last_state']??'never_checked')", source)
        self.assertIn('function p50_live_v4_discovery_rank', source)
        self.assertIn('function p50_live_v4_is_warm_watch', source)
        self.assertIn('function p50_live_v4_needs_tiktok_rescan', source)
        self.assertIn('function p50_live_v4_is_p0_tiktok', source)
        self.assertIn('function p50_live_v4_is_p0_source', source)
        self.assertIn('function p50_live_v4_merge_p0_watch', source)
        self.assertIn('webcast.tiktok.com/webcast/room/info_by_user', source)
        self.assertIn("'general-camille-makosso'", source)
        self.assertIn("'census-no-limit'", source)
        self.assertIn("'census-amour-ruth-poopy'", source)
        self.assertIn("'census-jordan-evraa'", source)
        self.assertIn("'census-jp-nda'", source)
        self.assertIn("'dbz'", source)
        self.assertIn("'maabio'", source)
        self.assertIn("'census-el-profesor'", source)
        self.assertIn("'census-sarara-messan'", source)
        self.assertIn("'louissette'", source)
        self.assertIn("'p_1785175190809'", source)
        self.assertIn("'aya-robert'", source)
        self.assertIn("'hamondchic'", source)
        self.assertIn("'dez-cocrane225'", source)
        self.assertIn('dezcocrane.225', source)
        self.assertNotIn("'census-roseline-layo'", source)
        self.assertNotIn('roselinelayoofficiel', source)
        self.assertIn("'census-rach-makosso'", source)
        self.assertIn('rach_makosso1', source)
        self.assertIn("'census-ange-morel'", source)
        self.assertIn('angemorel4', source)
        self.assertIn("'census-laguepe'", source)
        self.assertIn('laguepe03', source)
        self.assertIn("'census-rosemark-marcel'", source)
        self.assertIn('rosemarkmarcel', source)
        self.assertIn("'census-jiaan-wu'", source)
        self.assertIn('jiaaan.wu', source)
        self.assertIn('jiaaanwu', source)
        self.assertIn("'census-samuella-kouassi'", source)
        self.assertIn('samuellakouassiofficiel', source)
        self.assertIn("'census-bb-sans-os-de-man'", source)
        self.assertIn('bebe.sans.os.de.m', source)
        self.assertIn("'hassan'", source)
        self.assertIn('hassanhayekofficiel', source)
        self.assertIn("'census-le-grand-bicongo'", source)
        self.assertIn('legrandbicongo', source)
        self.assertIn("'census-chocolat-show-officiel'", source)
        self.assertIn('chocolat.show.officiel', source)
        self.assertIn("'census-la-legende'", source)
        self.assertIn('lalegende777', source)
        self.assertIn("'census-willway-jordan-officiel'", source)
        self.assertIn('jack.carter39', source)
        self.assertIn("'census-guyguy-le-grouilleur-de-bologne'", source)
        self.assertIn('guyguylegrouilleur07', source)
        self.assertIn("'census-souley-de-paris'", source)
        self.assertIn('souleydeparis', source)
        self.assertIn("'census-billal'", source)
        self.assertIn('billal_off2', source)
        self.assertIn("'census-ange-boli'", source)
        self.assertIn('angeboli7', source)
        self.assertIn('coachhamond', source)
        self.assertIn("'census-observateur-ebene'", source)
        self.assertIn("'oustaz-diane'", source)
        self.assertIn('OustazDianeofficiel', source)
        self.assertIn('function p50_live_v4_is_p0_youtube', source)
        self.assertIn('aya.robert27', source)
        self.assertIn('nolimit_vousdv', source)
        self.assertIn('realjordanevraa', source)
        self.assertIn('function p50_live_v4_is_unknown_tiktok', source)
        self.assertIn('P50_LIVE_V4_UNKNOWN_RESCAN_SECONDS', source)
        self.assertIn('function p50_live_v4_is_graph_fresh', source)
        self.assertIn("return [0,$tiktokFirst,'']", source)
        self.assertIn("return [1,0,$checked]", source)
        self.assertIn("new DateTimeZone('UTC')", source)
        self.assertIn("'meta_graph'", source)
        contract = (ROOT / 'api' / 'live-radar-contract.php').read_text(encoding='utf-8')
        self.assertIn("'radarVersion'=>'4.6'", contract)
        self.assertIn('coverageRevision', contract)

    def test_client_is_compatibly_loaded_but_uses_v4(self):
        self.assertIn("live-radar-v3.js?v=1.14", CONFIG)
        self.assertIn("const ENDPOINT='./api/live-status.php'", CLIENT)
        self.assertIn('RADAR LIVE V4', CLIENT)
        self.assertIn('TikTok:0', CLIENT)
        self.assertIn('PASS50_LIVE_EXPERIENCE_VERSION', EXPERIENCE)
        self.assertIn('live-trust-gate-v1.js?v=1.5', (ROOT / 'public-copy-fixes.js').read_text(encoding='utf-8'))
        self.assertIn('live-experience-v4-1.js?v=1.8', (ROOT / 'public-copy-fixes.js').read_text(encoding='utf-8'))

    def test_server_sweep_uses_v4(self):
        self.assertIn('*/5 * * * *', SWEEP)
        self.assertIn('api/live-status-v4.php', SWEEP)
        self.assertIn('mode=full', SWEEP)
        self.assertIn('live-radar-audit.json', SWEEP)
        self.assertIn('publishedStreams', SWEEP)
        self.assertIn('pass50/live-radar', SWEEP)
        quick = (ROOT / '.github' / 'workflows' / 'live-radar-quick.yml').read_text(encoding='utf-8')
        self.assertIn('*/5 * * * *', quick)
        self.assertIn('mode=quick', quick)
        self.assertIn('batch=16', quick)


if __name__ == '__main__':
    unittest.main()
