<?php
declare(strict_types=1);
$configFile=__DIR__.'/config.php'; if(!is_file($configFile)){http_response_code(503);exit('Configuration manquante.');}
$config=require $configFile; $d=$config['db'];
$pdo=new PDO(sprintf('mysql:host=%s;port=%d;dbname=%s;charset=%s',$d['host'],$d['port'],$d['name'],$d['charset']),$d['user'],$d['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$token=(string)($_REQUEST['token']??''); $message=''; $ok=false;
if($_SERVER['REQUEST_METHOD']==='POST'){
  $password=(string)($_POST['password']??''); $confirm=(string)($_POST['password_confirm']??'');
  if(strlen($password)<8)$message='Le mot de passe doit contenir au moins 8 caractères.';
  elseif($password!==$confirm)$message='Les deux mots de passe ne correspondent pas.';
  else{
    $stmt=$pdo->prepare('SELECT id FROM users WHERE reset_token_hash=? AND reset_expires_at>NOW() AND deleted_at IS NULL LIMIT 1');$stmt->execute([hash('sha256',$token)]);$id=$stmt->fetchColumn();
    if($id){$pdo->beginTransaction();$pdo->prepare('UPDATE users SET password_hash=?,reset_token_hash=NULL,reset_expires_at=NULL WHERE id=?')->execute([password_hash($password,PASSWORD_DEFAULT),$id]);$pdo->prepare('DELETE FROM sessions WHERE user_id=?')->execute([$id]);$pdo->commit();$ok=true;$message='Votre mot de passe a été modifié.';}else $message='Ce lien est invalide ou expiré.';
  }
}
$base=rtrim($config['app']['base_url'],'/');$home=htmlspecialchars($base,ENT_QUOTES);$logo=htmlspecialchars($base.'/assets/pass50-logo-email.png',ENT_QUOTES);$safeToken=htmlspecialchars($token,ENT_QUOTES);
?><!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mot de passe PASS50</title><body style="margin:0;background:#050705;color:#f6f8f4;font-family:Arial,sans-serif;display:grid;place-items:center;min-height:100vh"><main style="width:min(520px,calc(100% - 28px));padding:30px;border:1px solid #293129;border-radius:22px;background:#0d110d;box-sizing:border-box"><div style="text-align:center"><img src="<?= $logo ?>" alt="PASS50" style="width:min(360px,100%);height:auto"></div><h1 style="text-align:center;color:#b7ff00">Réinitialiser le mot de passe</h1><?php if($message):?><div style="padding:12px;border-radius:11px;background:<?= $ok?'#132b12':'#351111' ?>;color:<?= $ok?'#cfff9c':'#ffb1b1' ?>;margin-bottom:14px"><?= htmlspecialchars($message,ENT_QUOTES) ?></div><?php endif;?><?php if(!$ok):?><form method="post"><input type="hidden" name="token" value="<?= $safeToken ?>"><label style="display:block;font-weight:bold;margin:12px 0 6px">Nouveau mot de passe</label><input name="password" type="password" minlength="8" required style="width:100%;box-sizing:border-box;padding:13px;border-radius:11px;border:1px solid #394239;background:#111611;color:white"><label style="display:block;font-weight:bold;margin:12px 0 6px">Confirmer le mot de passe</label><input name="password_confirm" type="password" minlength="8" required style="width:100%;box-sizing:border-box;padding:13px;border-radius:11px;border:1px solid #394239;background:#111611;color:white"><button type="submit" style="margin-top:18px;width:100%;border:0;border-radius:12px;padding:14px;background:#b7ff00;color:#050705;font-weight:900;cursor:pointer">Enregistrer le nouveau mot de passe</button></form><?php else:?><a href="<?= $home ?>" style="display:block;text-align:center;margin-top:18px;padding:14px;border-radius:12px;background:#b7ff00;color:#050705;text-decoration:none;font-weight:900">Se connecter à PASS50</a><?php endif;?></main></body></html>